name: Test Terraform code

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY }}
      AWS_DEFAULT_REGION: eu-north-1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Setup Dependencies
      working-directory: ./
      run:  go get -v -t -d && go mod tidy

    - name: Test
      working-directory: ./
      run: go test -v
